### PR TITLE
Added config for dns-server patch

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
This patch is required for https://github.com/ipfs/go-ipfs/pull/6560

### CODE REVIEW

**Comment by lidel** [comment]
This is awesome, thank you for working on this!

I imagine we will want to support more than one DNS Resolver, to make it more robust:
- is the end goal to support both string  and array of strings?
- what will be the policy when more than one addr is provided? 
  try them in order/round-robin if the first one fails?

**Comment by ItalyPaleAle** [comment]
@lidel do you mind discussing the PR in https://github.com/ipfs/go-ipfs/pull/6560 to avoid forking?

I was not planning to add support for multiple DNS servers. Why do you think it's important - for HA?

My rationale for this PR was mostly to be able to support DNS servers running on localhost (which I believe includes TOR users too, according to an issue) and to support DNS-over-TLS servers like 1.1.1.1. Assuming that the DNS server on localhost is always up (by definition), for servers like Cloudflare's or Google's, they use multicast IP and they are incredibly reliable, and I think it's safe to assume they have 100% uptime. I believe that the idea of having multiple DNS resolvers is mostly a legacy thing and it's only applicable to those running DNS in corporate environments (like Active Directory) at this point.

But happy to discuss this :)

**Comment by matyapiro31** [comment]
I think this opttion is necessary for what I want to do.
I'm building custom dns server of OpenNIC domains, but to change all settings of server dns isn't good option.

**Comment by lidel** [comment]
FYSA go-ipfs-config got merged into go-ipfs repo: https://github.com/ipfs/go-ipfs/tree/master/config
If you feel this PR is still relevant, please reopen as a PR against go-ipfs

**Pull request closed without merging**
