### PR TITLE
Put /ws addrs in Addresses.Swarm by default

### PR DESCRIPTION
**Pull request by magik6k**
https://github.com/ipfs/go-ipfs/issues/5251

### CODE REVIEW

**Review by Stebalien — APPROVED** [review]

**Comment by whyrusleeping** [comment]
Can we not just enable a websocket dialer without adding a listener? Or am I misunderstanding?

**Comment by Stebalien** [comment]
We're trying to make it possible for nodes behind restrictive firewalls and mandatory HTTP proxies to dial *out* of their networks. Websockets use HTTP so these connections can be routed through corporate HTTP proxies. However, for this to work, other nodes have to be listening on the websocket transport to accept inbound websocket connections.

**Comment by Stebalien** [comment]
However, thinking about this a bit, we *may* need to wait until we can properly prioritize different transports in the dialer.

@raulk thoughts?

**Comment by hsanjuan** [comment]
Doesn't this also allow interop between browser js-ipfs and go-ipfs? That seems enough reason to enable it.

**Comment by hsanjuan** [comment]
nvm, just read the `wss` comment in the linked issue.

**Comment by bigs** [comment]
@Stebalien i think this would be a great thing to merge in after an initial pass of @raulk's dialer work lands. if we have a semi-concrete timeline for when that will land, i think we could even merge this now, knowing that it will be more appropriately prioritized soon.

**Comment by Stebalien** [comment]
Let's wait for the dialer work. While I'd like this, we *really* don't want the overhead of a `ws` connection when a normal `tcp` connection would suffice.

**Comment by lidel** [comment]
FYSA go-ipfs-config got merged into go-ipfs repo: https://github.com/ipfs/go-ipfs/tree/master/config
If you feel this PR is still relevant, please reopen as a PR against go-ipfs

**Pull request closed without merging**
